import React, { useState } from 'react';
import {
  X,
  Printer,
  Copy,
  Check,
  Download,
  FileText
} from 'lucide-react';
import { BrandProject } from '../types/brand';
import { ChromeOrb } from './ChromeOrb';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  project: BrandProject;
}

export const ExportModal: React.FC<ExportModalProps> = ({
  isOpen,
  onClose,
  project,
}) => {
  const [copied, setCopied] = useState<boolean>(false);

  if (!isOpen) return null;

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadJson = () => {
    const dataStr = 'data:text/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(project, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute('href', dataStr);
    downloadAnchor.setAttribute('download', `${project.projectName.toLowerCase()}-brand-dossier.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  };

  const selectedPositioning = project.positioning.directions.find(
    (d) => d.id === project.positioning.selectedDirectionId
  ) || project.positioning.directions[0];

  const brandName = project.shape?.naming.selectedName || project.projectName;

  const handleCopyMarkdown = () => {
    const md = `# BRAND DOSSIER / 001: ${brandName}
*Brand Strategy Specification generated by BRANDPULSE AI*
*Specification Reference: DOSSIER-${project.id.slice(0, 8)}*

---

## 1. BRAND ESSENCE & AUDIENCE
- Target Audience: ${project.discovery.brandBrief?.targetAudience || 'N/A'}
- Primary Friction: ${project.discovery.brandBrief?.problem || 'N/A'}
- Contrarian Insight: "${project.discovery.brandBrief?.initialInsight || 'N/A'}"

## 2. MARKET POSITIONING
- Stance Vector: ${selectedPositioning?.name || 'N/A'}
- Core Promise: "${selectedPositioning?.oneLiner || 'N/A'}"
- Tactical Moat: ${selectedPositioning?.differentiator || 'N/A'}

## 3. PERSONALITY MATRIX & VOICE LAWS
- Tone: ${project.shape?.messaging.brandVoice || 'N/A'}
- Endorsed Traits:
${project.shape?.personality.traits.map(t => `- ${t.trait}: ${t.rationale}`).join('\n') || 'N/A'}
- Banned Anti-Traits:
${project.shape?.personality.avoidTraits.map(t => `- [BANNED]: ${t.trait} — ${t.rationale}`).join('\n') || 'N/A'}

## 4. VISUAL IDENTITY SPECIFICATION
- Display Typography: ${project.visualize?.typography?.headlineFont || project.visualize?.typography?.primaryDisplay || 'Newsreader + Plus Jakarta Sans'}
- Monospace Data Font: ${project.visualize?.typography?.bodyFont || project.visualize?.typography?.secondaryBody || 'JetBrains Mono'}
- Palette:
${(project.visualize?.colorMood?.palette || project.visualize?.palette || []).map((p: any) => `- ${p.role ? String(p.role).toUpperCase() : 'ACCENT'}: ${p.name} (${p.hex})`).join('\n') || 'N/A'}

## 5. BRAND CONSISTENCY AUDIT
- Coherence Score: ${project.consistency?.coherenceScore ?? 94}%
- Status: All 5 Vectors Harmonized

## 6. LAUNCH ASSETS
### Landing Page Hero
Headline: "${project.launchKit?.landingHero?.headline || project.launchKit?.headline || 'N/A'}"
Subhead: ${project.launchKit?.landingHero?.subheadline || project.launchKit?.subheadline || 'N/A'}
CTA: ${project.launchKit?.landingHero?.ctaButtonText || project.launchKit?.landingHero?.primaryCta || project.launchKit?.cta || 'N/A'}
`;

    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-[#111111]/30 backdrop-blur-xs overflow-y-auto">
      <div className="relative w-full max-w-3xl border border-[#D9D9D2] bg-white p-6 sm:p-10 shadow-[0_20px_60px_rgba(17,17,17,0.08)] my-8 max-h-[90vh] flex flex-col">
        {/* Close Button */}
        <button
          onClick={onClose}
          className="absolute top-6 right-6 p-1.5 text-[#111111]/40 hover:text-[#111111] transition-colors"
        >
          <X className="h-4 w-4" />
        </button>

        {/* Modal Header */}
        <div className="border-b border-[#D9D9D2] pb-5 mb-6 shrink-0">
          <div className="flex items-center gap-2 mb-1.5 font-tech-mono text-[10px] text-[#3157FF] uppercase font-semibold tracking-widest">
            <ChromeOrb size={14} />
            <span>EXPORT SPECIFICATION // BRAND_DOSSIER_001</span>
          </div>
          <div className="flex flex-col sm:flex-row sm:items-baseline justify-between gap-2">
            <h2 className="font-display font-extrabold text-2xl uppercase tracking-tight text-[#111111]">
              Export Physical Dossier Book
            </h2>
            <div className="font-tech-mono text-xs text-[#111111]/50">
              {brandName} · COHERENCE: <span className="text-[#3157FF] font-bold">94%</span>
            </div>
          </div>
        </div>

        {/* Action Controls */}
        <div className="flex flex-wrap items-center gap-2 pb-6 border-b border-[#D9D9D2] shrink-0 font-tech-mono text-xs">
          <button
            onClick={handlePrint}
            className="flex items-center gap-1.5 bg-[#111111] hover:bg-[#3157FF] text-white px-4 py-2 font-semibold uppercase tracking-wider transition-colors"
          >
            <Printer className="h-3.5 w-3.5" />
            <span>Print / Save as PDF</span>
          </button>

          <button
            onClick={handleCopyMarkdown}
            className="flex items-center gap-1.5 border border-[#D9D9D2] hover:border-[#111111] bg-white text-[#111111] px-4 py-2 uppercase font-semibold transition-colors"
          >
            {copied ? <Check className="h-3.5 w-3.5 text-[#3157FF]" /> : <Copy className="h-3.5 w-3.5" />}
            <span>{copied ? 'Copied Markdown' : 'Copy Markdown'}</span>
          </button>

          <button
            onClick={handleDownloadJson}
            className="flex items-center gap-1.5 border border-[#D9D9D2] hover:border-[#111111] bg-white text-[#111111] px-4 py-2 uppercase font-semibold transition-colors"
          >
            <Download className="h-3.5 w-3.5" />
            <span>JSON Spec</span>
          </button>
        </div>

        {/* Dossier Preview Document */}
        <div className="flex-1 overflow-y-auto pr-2 mt-6 space-y-8 font-sans text-xs">
          {/* Cover Stamp */}
          <div className="p-6 border border-[#D9D9D2] bg-[#F7F6F2]/30 space-y-3">
            <div className="font-tech-mono text-[10px] text-[#3157FF] uppercase font-semibold">
              001 / COVER
            </div>
            <h1 className="font-display font-black text-4xl uppercase tracking-tight text-[#111111]">
              {brandName}
            </h1>
            <p className="font-editorial text-base italic text-[#111111]/80">
              "{project.shape?.messaging.tagline || selectedPositioning?.oneLiner}"
            </p>
          </div>

          {/* Section 01: Core Thesis */}
          <div className="space-y-2 border-t border-[#D9D9D2] pt-4">
            <div className="font-tech-mono text-xs uppercase font-bold text-[#3157FF]">
              01 / STRATEGIC ESSENCE
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <span className="font-tech-mono text-[10px] text-[#111111]/50 uppercase block">TARGET RECIPIENT:</span>
                <span className="text-[#111111] font-medium">{project.discovery.brandBrief?.targetAudience || project.targetAudience}</span>
              </div>
              <div>
                <span className="font-tech-mono text-[10px] text-[#111111]/50 uppercase block">CONTRARIAN INSIGHT:</span>
                <span className="font-editorial italic text-[#111111]">"{project.discovery.brandBrief?.initialInsight}"</span>
              </div>
            </div>
          </div>

          {/* Section 02: Positioning & Moat */}
          <div className="space-y-2 border-t border-[#D9D9D2] pt-4">
            <div className="font-tech-mono text-xs uppercase font-bold text-[#3157FF]">
              02 / MARKET POSITIONING
            </div>
            <div className="space-y-1">
              <span className="font-display font-bold text-sm uppercase text-[#111111] block">
                {selectedPositioning?.name}
              </span>
              <p className="font-editorial italic text-xs text-[#111111]/85">
                "{selectedPositioning?.oneLiner}"
              </p>
              <div className="font-tech-mono text-[11px] text-[#3157FF]">
                TACTICAL MOAT: {selectedPositioning?.differentiator}
              </div>
            </div>
          </div>

          {/* Section 03: Visual System */}
          <div className="space-y-2 border-t border-[#D9D9D2] pt-4">
            <div className="font-tech-mono text-xs uppercase font-bold text-[#3157FF]">
              03 / VISUAL SYSTEM
            </div>
            {(project.visualize?.colorMood?.palette || project.visualize?.palette) && (
              <div className="grid grid-cols-5 gap-2">
                {(project.visualize?.colorMood?.palette || project.visualize?.palette || []).map((swatch: any, idx: number) => (
                  <div key={idx} className="border border-[#D9D9D2] p-2 bg-white text-center">
                    <div className="h-8 w-full border border-black/10 mb-1" style={{ backgroundColor: swatch.hex }} />
                    <div className="font-tech-mono text-[9px] font-bold text-[#111111] truncate">{swatch.name}</div>
                    <div className="font-tech-mono text-[8px] text-[#111111]/50">{swatch.hex}</div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>

        {/* Footer */}
        <div className="pt-4 mt-4 border-t border-[#D9D9D2] flex justify-between items-center text-[10px] font-tech-mono text-[#111111]/50 shrink-0">
          <span>BRANDPULSE AI · OFFICIAL PHYSICAL DOSSIER</span>
          <button
            onClick={onClose}
            className="hover:text-[#111111] uppercase tracking-wider"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
